#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inotify-tools
Version  : 3.20.2.2
Release  : 7
URL      : https://github.com/inotify-tools/inotify-tools/releases/download/3.20.2.2/inotify-tools-3.20.2.2.tar.gz
Source0  : https://github.com/inotify-tools/inotify-tools/releases/download/3.20.2.2/inotify-tools-3.20.2.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: inotify-tools-bin = %{version}-%{release}
Requires: inotify-tools-lib = %{version}-%{release}
Requires: inotify-tools-license = %{version}-%{release}
Requires: inotify-tools-man = %{version}-%{release}

%description
![](https://github.com/inotify-tools/inotify-tools/workflows/build/badge.svg)
inotify-tools
=============

%package bin
Summary: bin components for the inotify-tools package.
Group: Binaries
Requires: inotify-tools-license = %{version}-%{release}

%description bin
bin components for the inotify-tools package.


%package dev
Summary: dev components for the inotify-tools package.
Group: Development
Requires: inotify-tools-lib = %{version}-%{release}
Requires: inotify-tools-bin = %{version}-%{release}
Provides: inotify-tools-devel = %{version}-%{release}
Requires: inotify-tools = %{version}-%{release}

%description dev
dev components for the inotify-tools package.


%package lib
Summary: lib components for the inotify-tools package.
Group: Libraries
Requires: inotify-tools-license = %{version}-%{release}

%description lib
lib components for the inotify-tools package.


%package license
Summary: license components for the inotify-tools package.
Group: Default

%description license
license components for the inotify-tools package.


%package man
Summary: man components for the inotify-tools package.
Group: Default

%description man
man components for the inotify-tools package.


%prep
%setup -q -n inotify-tools-3.20.2.2
cd %{_builddir}/inotify-tools-3.20.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1580697832
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1580697832
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/inotify-tools
cp %{_builddir}/inotify-tools-3.20.2.2/COPYING %{buildroot}/usr/share/package-licenses/inotify-tools/82b20355021c2d7ebf6bf6e58f8feb7ce35e09dc
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/inotifywait
/usr/bin/inotifywatch

%files dev
%defattr(-,root,root,-)
/usr/include/inotifytools/inotify-nosys.h
/usr/include/inotifytools/inotify.h
/usr/include/inotifytools/inotifytools.h
/usr/lib64/libinotifytools.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinotifytools.so.0
/usr/lib64/libinotifytools.so.0.4.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/inotify-tools/82b20355021c2d7ebf6bf6e58f8feb7ce35e09dc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/inotifywait.1
/usr/share/man/man1/inotifywatch.1
