#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : inotify-tools
Version  : 3.14
Release  : 2
URL      : https://github.com/rvoicilas/inotify-tools/archive/v3.14.tar.gz
Source0  : https://github.com/rvoicilas/inotify-tools/archive/v3.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: inotify-tools-bin
Requires: inotify-tools-lib
Requires: inotify-tools-doc

%description
inotify-tools
=============
This is a package of some commandline utilities relating to inotify.

%package bin
Summary: bin components for the inotify-tools package.
Group: Binaries

%description bin
bin components for the inotify-tools package.


%package dev
Summary: dev components for the inotify-tools package.
Group: Development
Requires: inotify-tools-lib
Requires: inotify-tools-bin
Provides: inotify-tools-devel

%description dev
dev components for the inotify-tools package.


%package doc
Summary: doc components for the inotify-tools package.
Group: Documentation

%description doc
doc components for the inotify-tools package.


%package lib
Summary: lib components for the inotify-tools package.
Group: Libraries

%description lib
lib components for the inotify-tools package.


%prep
%setup -q -n inotify-tools-3.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513293756
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1513293756
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/inotifywait
/usr/bin/inotifywatch

%files dev
%defattr(-,root,root,-)
/usr/include/inotifytools/inotify-nosys.h
/usr/include/inotifytools/inotify.h
/usr/include/inotifytools/inotifytools.h
/usr/lib64/libinotifytools.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinotifytools.so.0
/usr/lib64/libinotifytools.so.0.4.1
