#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v3
# autospec commit: ab27b0e7ad12
#
Name     : inotify-tools
Version  : 4.23.9.0
Release  : 15
URL      : https://github.com/inotify-tools/inotify-tools/archive/4.23.9.0/inotify-tools-4.23.9.0.tar.gz
Source0  : https://github.com/inotify-tools/inotify-tools/archive/4.23.9.0/inotify-tools-4.23.9.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: inotify-tools-bin = %{version}-%{release}
Requires: inotify-tools-lib = %{version}-%{release}
Requires: inotify-tools-license = %{version}-%{release}
Requires: inotify-tools-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![GitHub Build Status](https://github.com/inotify-tools/inotify-tools/workflows/build/badge.svg)](https://github.com/inotify-tools/inotify-tools/actions)
[![Travis Build Status](https://travis-ci.com/inotify-tools/inotify-tools.svg?branch=master)](https://travis-ci.com/inotify-tools/inotify-tools)
[![Cirrus Build Status](https://api.cirrus-ci.com/github/inotify-tools/inotify-tools.svg?branch=master)](https://cirrus-ci.com/github/inotify-tools/inotify-tools)
[![Coverity Build Status](https://scan.coverity.com/projects/23295/badge.svg)](https://scan.coverity.com/projects/inotifytools)
[![Coverage Status](https://codecov.io/gh/inotify-tools/inotify-tools/coverage.svg?branch=master)](https://codecov.io/gh/inotify-tools/inotify-tools?branch=master)

%package bin
Summary: bin components for the inotify-tools package.
Group: Binaries
Requires: inotify-tools-license = %{version}-%{release}

%description bin
bin components for the inotify-tools package.


%package dev
Summary: dev components for the inotify-tools package.
Group: Development
Requires: inotify-tools-lib = %{version}-%{release}
Requires: inotify-tools-bin = %{version}-%{release}
Provides: inotify-tools-devel = %{version}-%{release}
Requires: inotify-tools = %{version}-%{release}

%description dev
dev components for the inotify-tools package.


%package lib
Summary: lib components for the inotify-tools package.
Group: Libraries
Requires: inotify-tools-license = %{version}-%{release}

%description lib
lib components for the inotify-tools package.


%package license
Summary: license components for the inotify-tools package.
Group: Default

%description license
license components for the inotify-tools package.


%package man
Summary: man components for the inotify-tools package.
Group: Default

%description man
man components for the inotify-tools package.


%prep
%setup -q -n inotify-tools-4.23.9.0
cd %{_builddir}/inotify-tools-4.23.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1704412051
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1704412051
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/inotify-tools
cp %{_builddir}/inotify-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/inotify-tools/82b20355021c2d7ebf6bf6e58f8feb7ce35e09dc || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsnotifywait
/usr/bin/fsnotifywatch
/usr/bin/inotifywait
/usr/bin/inotifywatch

%files dev
%defattr(-,root,root,-)
/usr/include/inotifytools/fanotify-dfid-name.h
/usr/include/inotifytools/fanotify.h
/usr/include/inotifytools/inotify-nosys.h
/usr/include/inotifytools/inotify.h
/usr/include/inotifytools/inotifytools.h
/usr/lib64/libinotifytools.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinotifytools.so.0
/usr/lib64/libinotifytools.so.0.4.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/inotify-tools/82b20355021c2d7ebf6bf6e58f8feb7ce35e09dc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fsnotifywait.1
/usr/share/man/man1/fsnotifywatch.1
/usr/share/man/man1/inotifywait.1
/usr/share/man/man1/inotifywatch.1
